//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Loreal_DEVEntities3 : DbContext
    {
        public Loreal_DEVEntities3()
            : base("name=Loreal_DEVEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<V_QuestionDetails> V_QuestionDetails { get; set; }
    
        public virtual ObjectResult<GetAnswers_Result> GetAnswers(string year, Nullable<int> bookID, Nullable<int> versionID)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            var bookIDParameter = bookID.HasValue ?
                new ObjectParameter("BookID", bookID) :
                new ObjectParameter("BookID", typeof(int));
    
            var versionIDParameter = versionID.HasValue ?
                new ObjectParameter("VersionID", versionID) :
                new ObjectParameter("VersionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAnswers_Result>("GetAnswers", yearParameter, bookIDParameter, versionIDParameter);
        }
    }
}
