//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumDiscountRate
    {
        public int PremiumDiscountRateID { get; set; }
        public string Year { get; set; }
        public int BookID { get; set; }
        public decimal AdvertorialEarnedPercentDiscount { get; set; }
        public decimal BleedOpenPercentPremium { get; set; }
        public decimal BleedEarnedPercentPremium { get; set; }
        public decimal Cover2OpenPercentPremium { get; set; }
        public decimal Cover2EarnedPercentPremium { get; set; }
        public decimal Cover3OpenPercentPremium { get; set; }
        public decimal Cover3EarnedPercentPremium { get; set; }
        public decimal Cover4OpenPercentPremium { get; set; }
        public decimal Cover4EarnedPercentPremium { get; set; }
        public decimal FracHalfPageOpenPercentPremium { get; set; }
        public decimal FracHalfPageEarnedPercentPremium { get; set; }
        public decimal FracThirdPageOpenPercentPremium { get; set; }
        public decimal FracThirdPageEarnedPercentPremium { get; set; }
        public decimal FracThirdRunOppFBPOpenPercentPremium { get; set; }
        public decimal FracThirdRunOppFBPEarnedPercentPremium { get; set; }
        public decimal SpreadC2P1EarnedPercentDiscount { get; set; }
        public decimal SpreadROBEarnedPercentDiscount { get; set; }
        public int FifthColorMetallicOpenDollarPremium { get; set; }
        public int FifthColorMetallicEarnedDollarPremium { get; set; }
        public int FifthColorMatchOpenDollarPremium { get; set; }
        public int FifthColorMatchEarnedDollarPremium { get; set; }
        public int FifthColorPMSOpenDollarPremium { get; set; }
        public int FifthColorPMSEarnedDollarPremium { get; set; }
        public int VersionID { get; set; }
        public System.DateTime Load_Date { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
