//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int RateID { get; set; }
        public string Year { get; set; }
        public int BookID { get; set; }
        public int AdTypeID { get; set; }
        public int EditionTypeID { get; set; }
        public int RateTypeID { get; set; }
        public int TierID { get; set; }
        public decimal Rate1 { get; set; }
        public string OpenOrEarned { get; set; }
        public decimal CPM { get; set; }
        public string PublisherAgreement { get; set; }
        public int VersionID { get; set; }
        public System.DateTime Load_Date { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual Book Book { get; set; }
        public virtual EditionType EditionType { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual Tier Tier { get; set; }
    }
}
