//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loreal_print.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tier
    {
        public string Year { get; set; }
        public int BookID { get; set; }
        public int TierID { get; set; }
        public string Tier { get; set; }
        public string Tier_Range { get; set; }
    }
}
